services:
  mi-app:
    container_name: bulc-perros
    build: .
    image: bulc-perros:v1
    ports:
      - 8081:8081
    expose:
      - 8081
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge