services:
  mi-app:
    container_name: bulc-perros1
    build: .
    image: bulc-perros:v1
    ports:
      - 80:80
      - 443:443
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
